import { supabase } from '../supabaseClient';
import { SchoolProfile } from '../types';
import { INITIAL_SCHOOL_PROFILE } from '../data/initialData';

export const PROFIL_SEKOLAH_TABLE = 'profil_sekolah';
const LOCAL_STORAGE_KEY = 'sdn06_school_profile_cache';

export interface ColumnDefinition {
  name: string;
  type: string;
  description: string;
  fieldInApp: keyof SchoolProfile;
  example: string;
}

export const COLUMNS_DOCUMENTATION: ColumnDefinition[] = [
  { name: 'id', type: 'BIGINT (Primary Key)', description: 'ID unik baris profil sekolah (otomatis)', fieldInApp: 'schoolName', example: '1' },
  { name: 'nama_sekolah', type: 'TEXT', description: 'Nama resmi sekolah (Kop surat & kartu)', fieldInApp: 'schoolName', example: 'SD NEGERI KARANGGINTUNG 06' },
  { name: 'npsn', type: 'TEXT', description: 'Nomor Pokok Sekolah Nasional', fieldInApp: 'npsn', example: '20502106' },
  { name: 'instansi', type: 'TEXT', description: 'Nama instansi dinas pendidikan pembina', fieldInApp: 'educationAgency', example: 'PEMERINTAH KABUPATEN GRESIK • DINAS PENDIDIKAN' },
  { name: 'alamat', type: 'TEXT', description: 'Alamat lengkap lokasi sekolah', fieldInApp: 'address', example: 'Jl. Raya Karanggintung No. 06' },
  { name: 'kota', type: 'TEXT', description: 'Kota atau Kabupaten sekolah', fieldInApp: 'city', example: 'Gresik' },
  { name: 'kecamatan', type: 'TEXT', description: 'Kecamatan / unit wilayah sekolah', fieldInApp: 'district', example: 'Dinas Pendidikan' },
  { name: 'tahun_ajaran', type: 'TEXT', description: 'Tahun pelajaran aktif', fieldInApp: 'academicYear', example: '2025/2026' },
  { name: 'semester', type: 'TEXT', description: 'Semester aktif (Ganjil / Genap)', fieldInApp: 'semester', example: 'Ganjil' },
  { name: 'nama_kepsek', type: 'TEXT', description: 'Nama lengkap Kepala Sekolah & gelar', fieldInApp: 'principalName', example: 'Drs. Bambang Hariyanto, M.Pd.' },
  { name: 'nip_kepsek', type: 'TEXT', description: 'NIP Kepala Sekolah untuk pengesahan', fieldInApp: 'principalNip', example: '19690815 199303 1 004' },
  { name: 'nama_guru', type: 'TEXT', description: 'Nama Guru / Wali Kelas penandatangan', fieldInApp: 'teacherName', example: 'Nurul Hidayati, S.Pd.' },
  { name: 'nip_guru', type: 'TEXT', description: 'NIP Guru / Wali Kelas', fieldInApp: 'teacherNip', example: '19870322 201101 2 015' },
  { name: 'jam_masuk', type: 'TEXT', description: 'Batas jam datang kelas 3, 4, 5, 6 (HH:mm)', fieldInApp: 'checkInTime', example: '07:00' },
  { name: 'jam_pulang', type: 'TEXT', description: 'Batas mulai pulang kelas 3, 4, 5, 6 (HH:mm)', fieldInApp: 'checkOutTime', example: '13:00' },
  { name: 'jam_masuk_bawah', type: 'TEXT', description: 'Batas jam datang kelas 1 & 2 (HH:mm)', fieldInApp: 'checkInTimeLower', example: '07:00' },
  { name: 'jam_pulang_bawah', type: 'TEXT', description: 'Batas mulai pulang kelas 1 & 2 (HH:mm)', fieldInApp: 'checkOutTimeLower', example: '10:00' },
  { name: 'logo_url', type: 'TEXT', description: 'URL gambar atau Data URI (Base64) Logo Sekolah', fieldInApp: 'logoUrl', example: 'data:image/png;base64,...' },
  { name: 'updated_at', type: 'TIMESTAMPTZ', description: 'Waktu perubahan terakhir dicatat', fieldInApp: 'schoolName', example: '2026-09-14 10:00:00+00' },
];

export const SQL_CREATE_TABLE_SCRIPT = `-- ============================================================
-- SCRIPT PEMBUATAN TABEL PROFIL SEKOLAH DI SUPABASE
-- Salin dan jalankan seluruh baris kode ini di menu SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS public.profil_sekolah (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nama_sekolah TEXT NOT NULL DEFAULT 'SD NEGERI KARANGGINTUNG 06',
  npsn TEXT DEFAULT '20502106',
  instansi TEXT DEFAULT 'PEMERINTAH KABUPATEN GRESIK • DINAS PENDIDIKAN',
  alamat TEXT DEFAULT 'Jl. Raya Karanggintung No. 06',
  kota TEXT DEFAULT 'Gresik',
  kecamatan TEXT DEFAULT 'Dinas Pendidikan',
  tahun_ajaran TEXT DEFAULT '2025/2026',
  semester TEXT DEFAULT 'Ganjil',
  nama_kepsek TEXT DEFAULT 'Drs. Bambang Hariyanto, M.Pd.',
  nip_kepsek TEXT DEFAULT '19690815 199303 1 004',
  nama_guru TEXT DEFAULT 'Nurul Hidayati, S.Pd.',
  nip_guru TEXT DEFAULT '19870322 201101 2 015',
  jam_masuk TEXT DEFAULT '07:00',
  jam_pulang TEXT DEFAULT '13:00',
  jam_masuk_bawah TEXT DEFAULT '07:00',
  jam_pulang_bawah TEXT DEFAULT '10:00',
  logo_url TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mengaktifkan Row Level Security (RLS) dengan hak akses baca & tulis terbuka untuk anonim
ALTER TABLE public.profil_sekolah ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read profil_sekolah" ON public.profil_sekolah;
CREATE POLICY "Allow public read profil_sekolah" 
  ON public.profil_sekolah FOR SELECT 
  USING (true);

DROP POLICY IF EXISTS "Allow public insert profil_sekolah" ON public.profil_sekolah;
CREATE POLICY "Allow public insert profil_sekolah" 
  ON public.profil_sekolah FOR INSERT 
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update profil_sekolah" ON public.profil_sekolah;
CREATE POLICY "Allow public update profil_sekolah" 
  ON public.profil_sekolah FOR UPDATE 
  USING (true) 
  WITH CHECK (true);

-- Tambahkan tabel profil_sekolah ke publikasi realtime Supabase
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'profil_sekolah'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.profil_sekolah;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    NULL; -- Lanjut jika publikasi default sudah aktif
END $$;

-- Masukkan 1 baris awal sebagai data identitas utama (ID: 1)
INSERT INTO public.profil_sekolah (
  id, nama_sekolah, npsn, instansi, alamat, kota, kecamatan,
  tahun_ajaran, semester, nama_kepsek, nip_kepsek, nama_guru, nip_guru,
  jam_masuk, jam_pulang, jam_masuk_bawah, jam_pulang_bawah
) VALUES (
  1,
  'SD NEGERI KARANGGINTUNG 06',
  '20502106',
  'PEMERINTAH KABUPATEN GRESIK • DINAS PENDIDIKAN',
  'Jl. Raya Karanggintung No. 06',
  'Gresik',
  'Dinas Pendidikan',
  '2025/2026',
  'Ganjil',
  'Drs. Bambang Hariyanto, M.Pd.',
  '19690815 199303 1 004',
  'Nurul Hidayati, S.Pd.',
  '19870322 201101 2 015',
  '07:00',
  '13:00',
  '07:00',
  '10:00'
) ON CONFLICT (id) DO NOTHING;
`;

/**
 * Mapping data dari row database Supabase ke interface SchoolProfile aplikasi.
 * Mendukung format kolom bahasa Indonesia maupun format alternatif (snake_case/camelCase).
 */
export function mapDbToSchoolProfile(db: any): SchoolProfile {
  if (!db) return INITIAL_SCHOOL_PROFILE;

  return {
    schoolName: db.nama_sekolah || db.school_name || db.schoolName || INITIAL_SCHOOL_PROFILE.schoolName,
    npsn: db.npsn || INITIAL_SCHOOL_PROFILE.npsn,
    educationAgency: db.instansi || db.nama_instansi || db.education_agency || db.educationAgency || INITIAL_SCHOOL_PROFILE.educationAgency,
    address: db.alamat || db.address || INITIAL_SCHOOL_PROFILE.address,
    city: db.kota || db.city || INITIAL_SCHOOL_PROFILE.city,
    district: db.kecamatan || db.district || INITIAL_SCHOOL_PROFILE.district,
    academicYear: db.tahun_ajaran || db.academic_year || db.academicYear || INITIAL_SCHOOL_PROFILE.academicYear,
    semester: db.semester || INITIAL_SCHOOL_PROFILE.semester,
    principalName: db.nama_kepsek || db.nama_kepala_sekolah || db.principal_name || db.principalName || INITIAL_SCHOOL_PROFILE.principalName,
    principalNip: db.nip_kepsek || db.nip_kepala_sekolah || db.principal_nip || db.principalNip || INITIAL_SCHOOL_PROFILE.principalNip,
    teacherName: db.nama_guru || db.teacher_name || db.teacherName || INITIAL_SCHOOL_PROFILE.teacherName,
    teacherNip: db.nip_guru || db.teacher_nip || db.teacherNip || INITIAL_SCHOOL_PROFILE.teacherNip,
    checkInTime: db.jam_masuk || db.check_in_time || db.checkInTime || INITIAL_SCHOOL_PROFILE.checkInTime || '07:00',
    checkOutTime: db.jam_pulang || db.check_out_time || db.checkOutTime || INITIAL_SCHOOL_PROFILE.checkOutTime || '13:00',
    checkInTimeLower: db.jam_masuk_bawah || db.check_in_time_lower || db.checkInTimeLower || '07:00',
    checkOutTimeLower: db.jam_pulang_bawah || db.check_out_time_lower || db.checkOutTimeLower || '10:00',
    logoUrl: db.logo_url || db.logo || db.logoUrl || undefined,
  };
}

/**
 * Mapping data SchoolProfile ke format kolom database Supabase.
 */
export function mapSchoolProfileToDb(profile: SchoolProfile, existingId: any = 1) {
  return {
    id: existingId || 1,
    nama_sekolah: profile.schoolName || '',
    npsn: profile.npsn || '',
    instansi: profile.educationAgency || '',
    alamat: profile.address || '',
    kota: profile.city || '',
    kecamatan: profile.district || '',
    tahun_ajaran: profile.academicYear || '',
    semester: profile.semester || 'Ganjil',
    nama_kepsek: profile.principalName || '',
    nip_kepsek: profile.principalNip || '',
    nama_guru: profile.teacherName || '',
    nip_guru: profile.teacherNip || '',
    jam_masuk: profile.checkInTime || '07:00',
    jam_pulang: profile.checkOutTime || '13:00',
    jam_masuk_bawah: profile.checkInTimeLower || '07:00',
    jam_pulang_bawah: profile.checkOutTimeLower || '10:00',
    logo_url: profile.logoUrl || null,
    updated_at: new Date().toISOString(),
  };
}

/**
 * Mengambil data profil sekolah dari Supabase.
 * Mengembalikan profil dan status apakah tabel sudah ada di Supabase.
 */
export async function fetchSchoolProfileFromSupabase(): Promise<{
  profile: SchoolProfile;
  tableExists: boolean;
  rowId: any;
  error?: string;
}> {
  try {
    const { data, error } = await supabase
      .from(PROFIL_SEKOLAH_TABLE)
      .select('*')
      .order('id', { ascending: true })
      .limit(1);

    if (error) {
      // Error code 42P01: undefined_table (tabel belum dibuat)
      // Error code PGRST204 / schema cache error
      const isMissingTable =
        error.code === '42P01' ||
        error.message?.toLowerCase().includes('could not find the table') ||
        error.message?.toLowerCase().includes('relation') ||
        error.message?.toLowerCase().includes('schema cache');

      console.warn('Supabase fetchSchoolProfile error:', error.message);

      // Coba ambil dari local cache jika ada
      const cached = getCachedSchoolProfile();
      return {
        profile: cached || INITIAL_SCHOOL_PROFILE,
        tableExists: !isMissingTable,
        rowId: 1,
        error: error.message,
      };
    }

    if (data && data.length > 0) {
      const dbRow = data[0];
      const mapped = mapDbToSchoolProfile(dbRow);
      // Simpan ke local cache agar saat offline tetap ada
      cacheSchoolProfile(mapped);
      return {
        profile: mapped,
        tableExists: true,
        rowId: dbRow.id,
      };
    }

    // Tabel ada tetapi masih kosong
    return {
      profile: INITIAL_SCHOOL_PROFILE,
      tableExists: true,
      rowId: 1,
    };
  } catch (err: any) {
    console.error('Unexpected error fetching school profile:', err);
    return {
      profile: getCachedSchoolProfile() || INITIAL_SCHOOL_PROFILE,
      tableExists: false,
      rowId: 1,
      error: err?.message || 'Gagal terhubung ke Supabase',
    };
  }
}

/**
 * Menyimpan atau memperbarui profil sekolah ke Supabase.
 */
export async function saveSchoolProfileToSupabase(
  profile: SchoolProfile,
  existingId: any = 1
): Promise<{
  success: boolean;
  profile: SchoolProfile;
  error?: string;
  tableExists?: boolean;
}> {
  // Simpan ke local cache seketika
  cacheSchoolProfile(profile);

  try {
    const payload = mapSchoolProfileToDb(profile, existingId);
    const { data, error } = await supabase
      .from(PROFIL_SEKOLAH_TABLE)
      .upsert(payload, { onConflict: 'id' })
      .select();

    if (error) {
      const isMissingTable =
        error.code === '42P01' ||
        error.message?.toLowerCase().includes('could not find the table') ||
        error.message?.toLowerCase().includes('schema cache');

      console.error('Supabase saveSchoolProfile error:', error);
      return {
        success: false,
        profile,
        error: error.message,
        tableExists: !isMissingTable,
      };
    }

    const savedRow = data && data.length > 0 ? data[0] : payload;
    const mapped = mapDbToSchoolProfile(savedRow);
    cacheSchoolProfile(mapped);

    return {
      success: true,
      profile: mapped,
      tableExists: true,
    };
  } catch (err: any) {
    console.error('Unexpected error saving school profile:', err);
    return {
      success: false,
      profile,
      error: err?.message || 'Terjadi kesalahan sistem saat menyimpan ke Supabase.',
    };
  }
}

/**
 * Berlangganan (realtime subscription) perubahan tabel profil_sekolah.
 * Menjamin semua perangkat terhubung langsung menerima pembaruan secara live.
 */
export function subscribeSchoolProfileRealtime(
  onUpdate: (updatedProfile: SchoolProfile) => void
) {
  try {
    const channel = supabase
      .channel('profil_sekolah_realtime_channel')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: PROFIL_SEKOLAH_TABLE },
        (payload) => {
          if (payload.new) {
            const mapped = mapDbToSchoolProfile(payload.new);
            cacheSchoolProfile(mapped);
            onUpdate(mapped);
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  } catch (err) {
    console.warn('Gagal menginisialisasi Realtime channel Supabase:', err);
    return () => {};
  }
}

/**
 * Cache lokal pembantu untuk persistensi sementara sebelum tabel Supabase dibuat.
 */
function cacheSchoolProfile(profile: SchoolProfile) {
  try {
    if (typeof window !== 'undefined' && window.localStorage) {
      localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(profile));
    }
  } catch {
    // Abaikan jika storage quota penuh
  }
}

export function getCachedSchoolProfile(): SchoolProfile | null {
  try {
    if (typeof window !== 'undefined' && window.localStorage) {
      const raw = localStorage.getItem(LOCAL_STORAGE_KEY);
      if (raw) return JSON.parse(raw);
    }
  } catch {
    return null;
  }
  return null;
}
